mod collection_detail;
mod collection_list;
mod dashboard;
mod explore;
mod home;
mod login;
mod not_found;
mod recipe_detail;
mod recipe_new;
mod settings;

pub use collection_detail::CollectionDetail;
pub use collection_list::CollectionList;
pub use dashboard::Dashboard;
pub use explore::Explore;
pub use home::Home;
pub use login::Login;
pub use not_found::NotFound;
pub use recipe_detail::RecipeDetail;
pub use recipe_new::RecipeNew;
pub use settings::SettingsAccounts;
pub use settings::SettingsProfile;
